    function injectStyles() {
        // 清理任何残留的旧样式表：历史上多次热注入可能留下了无 id 的 <style>，
        // 把 #xsact-qa-panel 的 background 写死成字面量，盖过本脚本的主题变量，
        // 导致主题切换“看似没反应”。凡含本面板选择器且非本脚本样式表的一律移除。
        try {
            Array.prototype.forEach.call(document.querySelectorAll('style'), function(s) {
                if (s.id !== 'xsact-qa-styles' && s.textContent && s.textContent.indexOf('#xsact-qa-panel') !== -1) {
                    s.parentNode && s.parentNode.removeChild(s);
                }
            });
        } catch (_) { /* 忽略：清理旧样式表失败无影响 */ }
        // 已存在则覆盖内容：避免旧版本残留的样式表（只有 dark-rose 等旧主题名）
        // 导致新版 data-xsact-theme="dark/light" 匹配不到规则、主题切换失效。
        var css = document.getElementById('xsact-qa-styles');
        if (!css) {
            css = document.createElement('style');
            css.id = 'xsact-qa-styles';
            document.head.appendChild(css);
        }
        css.textContent = [
            buildThemeVarsCSS(),
            /* 统一图标基样式 */
            '.xsact-ico{display:block;flex-shrink:0;}',

            /* ===== DOM 切换按钮（固定右下角，永远可见） ===== */
            '#xsact-toggle-btn{',
            '  position:fixed;bottom:72px;right:16px;z-index:100000;',
            '  width:44px;height:44px;border-radius:13px;',
            '  background:rgba(var(--xs-accent-rgb), 0.85);border:2px solid rgba(var(--xs-accent-rgb), 0.5);',
            '  color:#fff;cursor:pointer;display:flex;align-items:center;justify-content:center;',
            '  backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);',
            '  box-shadow:0 4px 16px var(--xs-shadow),0 0 8px rgba(var(--xs-accent-rgb), 0.2);',
            '  transition:all 0.2s ease;outline:none;',
            '}',
            '#xsact-toggle-btn:hover{',
            '  background:rgba(var(--xs-accent-rgb), 1);border-color:var(--xs-accent);',
            '  box-shadow:0 6px 24px var(--xs-shadow),0 0 16px rgba(var(--xs-accent-rgb), 0.4);',
            '  transform:scale(1.08);',
            '}',
            '#xsact-toggle-btn.active{',
            '  background:rgba(70,224,160,0.9);border-color:#46E0A0;',
            '  box-shadow:0 4px 16px rgba(70,224,160,0.3),0 0 12px rgba(70,224,160,0.4);',
            '}',
            '#xsact-toggle-btn.active:hover{',
            '  background:#46E0A0;transform:scale(1.08);',
            '}',

            /* ===== 右侧面板（暗色战术操作台） ===== */
            '#xsact-qa-panel{',
            '  position:fixed;top:min(48px,4vh);right:12px;width:min(380px,92vw);height:min(680px,88vh);z-index:90000;',
            '  background:var(--xs-panel-bg);border-radius:14px;',
            '  border:1px solid var(--xs-border);',
            '  display:flex;flex-direction:column;box-sizing:border-box;',
            '  backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);',
            '  box-shadow:0 14px 44px var(--xs-shadow);',
            '  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"PingFang SC","Microsoft YaHei",sans-serif;',
            '  min-width:220px;min-height:300px;max-width:min(560px,96vw);max-height:min(88vh,820px);',
            '  transition:border-color .2s ease,box-shadow .2s ease;',
            '}',
            '#xsact-qa-panel.popover-open{',
            '  border-left-color:var(--xs-accent);',
            '  box-shadow:0 0 24px rgba(var(--xs-accent-rgb), 0.15),0 14px 44px var(--xs-shadow);',
            '}',
            '.xsact-qa-panel-inner{',
            '  display:flex;flex-direction:column;height:100%;min-width:0;min-height:0;box-sizing:border-box;container-type:inline-size;container-name:xsact-panel;',
            '  overflow:hidden;border-radius:14px;',
            '}',

            /* 标题栏 = 拖拽手柄 */
            '.xsact-qa-panel-header{',
            '  display:flex;justify-content:space-between;align-items:center;gap:8px;',
            '  padding:11px 12px 9px;border-bottom:1px solid var(--xs-border);',
            '  cursor:grab;user-select:none;-webkit-user-select:none;',
            '}',
            '.xsact-qa-panel-header.dragging{cursor:grabbing;}',
            '.xsact-panel-grip{color:var(--xs-text-faint);display:flex;transition:color .15s;}',
            '.xsact-qa-panel-header.dragging .xsact-panel-grip{color:var(--xs-accent);}',
            '#xsact-panel-title{',
            '  flex:1;min-width:0;font-size:13px;font-weight:600;color:var(--xs-text);',
            '  letter-spacing:0.3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;',
            '}',
            '.xsact-panel-head-actions{display:flex;gap:5px;flex-shrink:0;}',

            /* 模式切换标签 */
            '.xsact-qa-mode-tabs{',
            '  display:flex;gap:6px;padding:9px 12px 5px;',
            '}',
            '.xsact-mode-tab{',
            '  flex:1;padding:8px 8px;font-size:12px;cursor:pointer;',
            '  background:var(--xs-btn-bg);border:1px solid var(--xs-border);min-width:32px;min-height:32px;box-sizing:border-box;',
            '  border-radius:8px;color:var(--xs-text-dim);transition:all 0.15s ease;',
            '  display:flex;align-items:center;justify-content:center;gap:6px;',
            '}',
            '.xsact-mode-tab .xsact-ico{width:14px;height:14px;stroke-width:2.2px;}',
            '.xsact-mode-tab:hover{color:var(--xs-text);border-color:var(--xs-border-strong);}',
            '.xsact-mode-tab.active{',
            '  background:rgba(var(--xs-accent-rgb), 0.14);border-color:var(--xs-accent);color:var(--xs-accent-text);font-weight:600;',
            '}',

            /* 类型计数徽标 */
            '.xsact-type-count{',
            '  margin-left:auto;min-width:20px;text-align:center;',
            '  font-size:11px;font-weight:700;color:var(--xs-accent-text);',
            '  background:rgba(var(--xs-accent-rgb), 0.16);border-radius:9px;padding:1px 7px;',
            '}',

            '.xsact-qa-panel-body{',
            '  flex:1;overflow-y:auto;overflow-x:hidden;padding:10px 12px;overscroll-behavior:contain;',
            '  scrollbar-width:thin;scrollbar-color:var(--xs-scroll) transparent;',
            '  display:grid;grid-template-columns:repeat(auto-fill, minmax(108px, 1fr));gap:6px;min-width:0;container-type:inline-size;container-name:xsact-body;',
            '  align-content:start;min-height:0;',
            '}',
            '.xsact-qa-empty{',
            '  color:var(--xs-text-faint);text-align:center;padding:42px 14px;font-size:12px;line-height:1.6;grid-column:1 / -1;',
            '}',

            /* 动作按钮 */
            '.xsact-action-btn{',
            '  position:relative;overflow:hidden;',
            '  display:flex;align-items:center;gap:8px;',
            '  width:100%;padding:10px 11px;',
            '  background:var(--xs-panel-bg-2);border:1px solid var(--xs-border);',
            '  border-left:2px solid transparent;',
            '  border-radius:8px;color:var(--xs-text-dim);font-size:12.5px;cursor:pointer;',
            '  transition:background .15s ease,border-color .15s ease,color .15s ease,box-shadow .15s ease;text-align:left;',
            '}',
            '.xsact-action-btn:hover{',
            '  background:var(--xs-hover);border-color:var(--xs-border-strong);color:var(--xs-text);',
            '}',
            '.xsact-action-btn.sel{',
            '  background:rgba(var(--xs-accent-rgb), 0.12);border-color:var(--xs-accent);border-left-color:var(--xs-accent);color:var(--xs-accent-text);',
            '}',
            '.xsact-action-btn.fav{',
            '  background:rgba(232,179,57,0.12);border-color:rgba(232,179,57,0.55);border-left-color:#E8B339;color:#FCEBC0;',
            '  box-shadow:0 0 0 1px rgba(232,179,57,0.08) inset,0 0 12px rgba(232,179,57,0.15);',
            '}',
            '.xsact-action-btn.fav:hover{',
            '  background:rgba(232,179,57,0.20);border-color:rgba(232,179,57,0.75);color:#fff;',
            '}',
            '.xsact-action-label{flex:1;position:relative;z-index:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
            '.xsact-action-star{color:#E8B339;display:flex;position:relative;z-index:1;filter:drop-shadow(0 0 4px rgba(232,179,57,0.7));}',

            /* 动作行 + 加入组合按钮 */
            '.xsact-action-row{',
            '  display:flex;align-items:center;gap:6px;min-width:0;',
            '}',
            '.xsact-action-row .xsact-action-btn{flex:1;margin-bottom:0;width:auto;min-width:0;height:100%;}',
            '.xsact-add-to-combo{',
            '  width:30px;height:30px;flex-shrink:0;',
            '  background:rgba(70,224,160,0.12);border:1px solid rgba(70,224,160,0.4);',
            '  border-radius:8px;color:#46E0A0;cursor:pointer;',
            '  display:flex;align-items:center;justify-content:center;transition:all 0.15s ease;',
            '}',
            '.xsact-add-to-combo:hover{background:rgba(70,224,160,0.24);border-color:#46E0A0;color:#CFFAE8;}',

            /* 自定义组合卡片 */
            '.xsact-combo-card{',
            '  grid-column:1 / -1;',
            '  display:flex;justify-content:space-between;align-items:center;',
            '  padding:11px 12px;margin-bottom:7px;',
            '  background:var(--xs-panel-bg-2);border:1px solid var(--xs-border);',
            '  border-radius:9px;color:var(--xs-text-dim);',
            '}',
            '.xsact-combo-info{display:flex;flex-direction:column;gap:2px;min-width:0;}',
            '.xsact-combo-name{font-size:13px;font-weight:600;color:var(--xs-text);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
            '.xsact-combo-count{font-size:11px;color:var(--xs-text-faint);}',
            '.xsact-combo-btns{display:flex;gap:6px;}',
            '.xsact-combo-btns button{',
            '  width:30px;height:30px;border-radius:7px;cursor:pointer;',
            '  background:var(--xs-btn-bg);border:1px solid var(--xs-border-strong);',
            '  color:var(--xs-text-dim);display:flex;align-items:center;justify-content:center;transition:all 0.15s ease;',
            '}',
            '.xsact-combo-run:hover{background:rgba(var(--xs-accent-rgb), 0.18);border-color:var(--xs-accent);color:var(--xs-accent-text);}',
            '.xsact-combo-edit:hover{background:rgba(70,224,160,0.16);border-color:#46E0A0;color:#CFFAE8;}',
            '.xsact-combo-delete:hover{background:rgba(255,92,92,0.16);border-color:#FF5C5C;color:#FFB3B3;}',

            '.xsact-combo-new-btn{',
            '  grid-column:1 / -1;',
            '  width:100%;padding:10px;margin-top:7px;',
            '  background:rgba(var(--xs-accent-rgb), 0.08);border:1px dashed rgba(var(--xs-accent-rgb), 0.4);',
            '  border-radius:8px;color:var(--xs-accent-text);font-size:12.5px;cursor:pointer;',
            '  display:flex;align-items:center;justify-content:center;gap:6px;transition:all 0.15s ease;',
            '}',
            '.xsact-combo-new-btn:hover{background:rgba(var(--xs-accent-rgb), 0.16);color:#fff;}',

            /* 预设栏 */
            '.xsact-combo-editor{grid-column:1 / -1;display:flex;flex-direction:column;gap:11px;}',
            '.xsact-combo-field input{',
            '  width:100%;padding:8px 10px;box-sizing:border-box;',
            '  background:var(--xs-input-bg);border:1px solid var(--xs-border-strong);',
            '  border-radius:7px;color:var(--xs-text);font-size:13px;',
            '}',
            '.xsact-combo-field input:focus{outline:none;border-color:var(--xs-accent);}',
            '.xsact-combo-delay label{display:block;font-size:12px;color:var(--xs-text-dim);margin-bottom:6px;}',
            '.xsact-combo-delay #xsact-delay-val{color:var(--xs-accent);font-weight:700;}',
            '.xsact-combo-delay input[type=range]{width:100%;accent-color:var(--xs-accent);height:4px;cursor:pointer;}',
            '.xsact-combo-items{',
            '  display:flex;flex-direction:column;gap:6px;max-height:230px;overflow-y:auto;',
            '  scrollbar-width:thin;scrollbar-color:var(--xs-scroll) transparent;',
            '}',
            '.xsact-combo-item{',
            '  display:flex;align-items:center;gap:7px;padding:8px;',
            '  background:var(--xs-panel-bg-2);border:1px solid var(--xs-border);',
            '  border-radius:7px;font-size:12px;color:var(--xs-text-dim);',
            '}',
            '.xsact-combo-item-num{',
            '  min-width:18px;text-align:center;font-size:10px;font-weight:700;',
            '  color:var(--xs-accent-text);background:rgba(var(--xs-accent-rgb), 0.16);border-radius:5px;padding:1px 0;',
            '}',
            '.xsact-combo-item-part{',
            '  min-width:42px;color:var(--xs-text-faint);font-weight:500;',
            '}',
            '.xsact-combo-item-action{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
            '.xsact-combo-item button{',
            '  width:24px;height:24px;padding:0;border-radius:6px;cursor:pointer;',
            '  background:var(--xs-btn-bg);border:1px solid var(--xs-border-strong);',
            '  color:var(--xs-text-dim);display:flex;align-items:center;justify-content:center;transition:all 0.15s ease;',
            '}',
            '.xsact-combo-item-up:hover,.xsact-combo-item-down:hover{border-color:var(--xs-accent);color:var(--xs-accent-text);}',
            '.xsact-combo-item-del:hover{border-color:#FF5C5C;color:#FFB3B3;}',
            '.xsact-combo-actions{display:flex;gap:8px;}',
            '.xsact-combo-actions button{flex:1;padding:9px;border-radius:7px;cursor:pointer;font-size:13px;border:none;color:var(--xs-text);}',
            '.xsact-combo-save-btn{background:#46E0A0;color:#fff;}',
            '.xsact-combo-save-btn:hover{background:#2FC989;}',
            '.xsact-combo-cancel-btn{background:var(--xs-border);color:var(--xs-text);}',
            '.xsact-combo-cancel-btn:hover{background:var(--xs-border-strong);}',

            /* ===== 自定义动作（我的动作 tab） ===== */
            '#xsact-action-list.xsact-custom-mode{display:flex;flex-direction:column;gap:12px;padding:10px 12px;}',
            '#xsact-action-list.xsact-custom-mode > *{width:100%;min-width:0;}',
            '.xsact-ca-view{display:flex;flex-direction:column;gap:12px;width:100%;min-width:0;padding:2px 0;}',

            '.xsact-ca-toolbar{display:flex;align-items:center;gap:8px;width:100%;min-width:0;}',
            '.xsact-ca-search{flex:1;min-width:0;padding:9px 12px;border-radius:8px;border:1px solid var(--xs-border);background:var(--xs-input-bg);color:var(--xs-text);font-size:13px;transition:opacity .15s;}',
            '.xsact-ca-search:focus{outline:none;border-color:var(--xs-accent);}',
            '.xsact-ca-search.is-hidden{visibility:hidden;pointer-events:none;opacity:0;}',
            '.xsact-ca-toolbar-btns{display:flex;gap:6px;flex-shrink:0;}',
            '.xsact-ca-toolbar-btns button{display:flex;align-items:center;justify-content:center;gap:5px;width:34px;height:34px;padding:0;border-radius:8px;border:1px solid var(--xs-border);background:var(--xs-btn-bg);color:var(--xs-text-dim);cursor:pointer;font-size:12px;transition:background .15s,border-color .15s,color .15s;}',
            '.xsact-ca-toolbar-btns button:hover{background:var(--xs-hover);border-color:var(--xs-border-strong);color:var(--xs-text);}',
            '.xsact-ca-toolbar-btns button.xsact-ca-new{width:auto;padding:0 12px;background:rgba(255,92,122,0.14);border-color:rgba(255,92,122,0.45);color:#FF8FA6;}',
            '.xsact-ca-toolbar-btns button.xsact-ca-new:hover{background:rgba(255,92,122,0.24);color:#FFB3C6;}',

            '.xsact-ca-import-wrap{position:relative;display:flex;align-items:center;}',
            '.xsact-ca-import-menu{position:absolute;top:calc(100% + 6px);right:0;z-index:100;display:flex;flex-direction:column;gap:4px;min-width:150px;padding:6px;border-radius:8px;background:var(--xs-panel-bg);border:1px solid var(--xs-border);box-shadow:0 8px 24px rgba(0,0,0,0.35);}',
            '.xsact-ca-import-menu.hidden{display:none;}',
            '.xsact-ca-import-menu button{width:100%;justify-content:flex-start;padding:8px 10px;border-radius:6px;border:1px solid transparent;background:transparent;color:var(--xs-text);font-size:12px;text-align:left;cursor:pointer;transition:background .15s,border-color .15s;}',
            '.xsact-ca-import-menu button:hover{background:var(--xs-hover);border-color:var(--xs-border);}',
            '.xsact-ca-file-input{position:absolute;opacity:0;width:0;height:0;pointer-events:none;}',

            '.xsact-ca-beta{font-size:11px;line-height:1.55;color:var(--xs-accent-text);background:rgba(var(--xs-accent-rgb),0.10);border:1px solid rgba(var(--xs-accent-rgb),0.30);border-left:3px solid var(--xs-accent);border-radius:8px;padding:10px 12px;}',

            '.xsact-ca-echo-clean{display:flex;align-items:center;gap:12px;flex-wrap:wrap;font-size:11px;line-height:1.5;color:var(--xs-text);background:rgba(255,92,122,0.08);border:1px solid rgba(255,92,122,0.32);border-left:3px solid #FF5C7A;border-radius:8px;padding:10px 12px;margin-top:2px;}',
            '.xsact-ca-echo-clean-text{flex:1;min-width:160px;color:var(--xs-text-dim);}',
            '.xsact-ca-echo-clean-text b{color:#FF8FA6;font-weight:700;}',
            '.xsact-ca-echo-clean-btn{flex-shrink:0;display:inline-flex;align-items:center;justify-content:center;padding:7px 14px;border-radius:8px;border:1px solid rgba(255,92,122,0.5);background:rgba(255,92,122,0.16);color:#FFB3C6;font-size:12px;font-weight:600;cursor:pointer;transition:background .15s,border-color .15s,color .15s;}',
            '.xsact-ca-echo-clean-btn:hover{background:rgba(255,92,122,0.28);border-color:#FF5C7A;color:#FFFFFF;}',

            '.xsact-ca-list{display:flex;flex-direction:column;gap:10px;width:100%;}',
            '.xsact-ca-card{display:grid;grid-template-columns:1fr auto;align-items:center;gap:10px;padding:12px 14px;border-radius:10px;background:var(--xs-card-bg);border:1px solid var(--xs-border);transition:border-color .15s,background .15s,transform .1s;min-width:0;}',
            '.xsact-ca-card:hover{border-color:var(--xs-border-strong);background:var(--xs-hover);transform:translateY(-1px);}',
            '.xsact-ca-info{display:flex;flex-direction:column;gap:5px;min-width:0;overflow:hidden;}',
            '.xsact-ca-title{display:flex;align-items:center;gap:8px;min-width:0;}',
            '.xsact-ca-name{font-size:14px;font-weight:600;color:var(--xs-text);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
            '.xsact-ca-meta{display:flex;align-items:center;gap:8px;min-width:0;}',
            '.xsact-ca-part{font-size:11px;color:var(--xs-text-dim);opacity:.85;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
            '.xsact-ca-badge{flex-shrink:0;font-size:10px;padding:3px 8px;border-radius:20px;font-weight:600;letter-spacing:0.02em;}',
            '.xsact-ca-badge.other{background:rgba(90,160,255,0.16);color:#8FB8FF;}',
            '.xsact-ca-badge.self{background:rgba(70,224,160,0.16);color:#5FE3B0;}',
            '.xsact-ca-badge.any{background:rgba(255,92,122,0.16);color:#FF8FA6;}',
            '.xsact-ca-src{flex-shrink:0;font-size:10px;padding:2px 7px;border-radius:20px;font-weight:600;letter-spacing:0.02em;}',
            '.xsact-ca-src.echo{background:rgba(255,200,90,0.16);color:#FFD87A;}',
            '.xsact-ca-src.native{background:rgba(160,140,255,0.16);color:#C4B8FF;}',
            '.xsact-ca-card.is-hidden{opacity:.55;border-style:dashed;}',
            '.xsact-ca-editmode.is-active{background:rgba(255,92,122,0.22);border-color:rgba(255,92,122,0.55);color:#FFB3C6;}',
            '.xsact-ca-toggleall:hover{background:rgba(255,92,122,0.18);border-color:rgba(255,92,122,0.45);color:#FFB3C6;}',
            '.xsact-ca-toggleall.is-on{background:rgba(255,92,122,0.22);border-color:rgba(255,92,122,0.55);color:#FFB3C6;}',
            '.xsact-ca-toggleall.is-on:hover{background:rgba(255,92,122,0.32);color:#FFD6DF;}',
            '.xsact-ca-card.is-edit{grid-template-columns:auto 1fr auto;cursor:pointer;user-select:none;}',
            '.xsact-ca-card.is-edit:hover{transform:none;background:var(--xs-hover);}',
            '.xsact-ca-handle{display:flex;align-items:center;justify-content:center;width:20px;color:var(--xs-text-dim);cursor:grab;flex-shrink:0;}',
            '.xsact-ca-handle:active{cursor:grabbing;}',
            '.xsact-ca-card.is-selected{border-color:var(--xs-accent);background:rgba(var(--xs-accent-rgb),0.12);box-shadow:0 0 0 1px var(--xs-accent) inset;}',
            '.xsact-ca-check{display:none;align-items:center;justify-content:center;width:22px;height:22px;border-radius:50%;background:var(--xs-accent);color:#fff;flex-shrink:0;}',
            '.xsact-ca-card.is-selected .xsact-ca-check{display:flex;}',
            '.xsact-ca-card.dragging{opacity:.45;outline:2px dashed var(--xs-accent);outline-offset:-2px;}',
            '.xsact-ca-vis-dot{font-size:11px;padding:1px 8px;border-radius:999px;background:var(--xs-border-strong);color:var(--xs-text-dim);white-space:nowrap;}',
            '.xsact-ca-vis-dot.on{background:rgba(70,224,160,0.18);color:#46E0A0;}',
            '.xsact-ca-vis-dot.off{background:rgba(255,92,92,0.16);color:#FF9C9C;}',
            '.xsact-ca-select-all{padding:6px 12px;border-radius:6px;border:1px solid var(--xs-border);background:var(--xs-btn-bg);color:var(--xs-text);font-size:12px;cursor:pointer;transition:background .15s,border-color .15s;white-space:nowrap;}',
            '.xsact-ca-select-all:hover{background:var(--xs-hover);border-color:var(--xs-border-strong);}',
            '.xsact-ca-batchbar{display:flex;align-items:center;gap:10px;width:100%;min-width:0;padding:9px 12px;border-radius:8px;background:var(--xs-panel-bg-2);border:1px solid var(--xs-border);}',
            '.xsact-ca-selected-count{font-size:12px;color:var(--xs-text-dim);white-space:nowrap;margin-right:auto;}',
            '.xsact-ca-batch-actions{display:flex;gap:6px;flex-shrink:0;}',
            '.xsact-ca-batch-actions button{padding:6px 12px;border-radius:6px;border:1px solid var(--xs-border);background:var(--xs-btn-bg);color:var(--xs-text);font-size:12px;cursor:pointer;transition:background .15s,border-color .15s,color .15s;}',
            '.xsact-ca-batch-actions button:hover:not(:disabled){background:var(--xs-hover);border-color:var(--xs-border-strong);}',
            '.xsact-ca-batch-actions button:disabled{opacity:.45;cursor:not-allowed;}',
            '.xsact-ca-batch-del{background:rgba(255,92,92,0.12);border-color:rgba(255,92,92,0.35);color:#FF9C9C;}',
            '.xsact-ca-batch-del:hover:not(:disabled){background:rgba(255,92,92,0.22);border-color:rgba(255,92,92,0.5);}',
            '.xsact-ca-toggle{display:flex;align-items:center;gap:7px;cursor:pointer;font-size:11px;color:var(--xs-text-dim);}',
            '.xsact-ca-toggle input{position:absolute;opacity:0;width:0;height:0;}',
            '.xsact-ca-toggle-track{width:34px;height:18px;border-radius:999px;background:var(--xs-border-strong);position:relative;transition:background .2s;}',
            '.xsact-ca-toggle-track::before{content:"";position:absolute;left:2px;top:2px;width:14px;height:14px;border-radius:50%;background:#fff;transition:transform .2s;}',
            '.xsact-ca-toggle input:checked + .xsact-ca-toggle-track{background:var(--xs-accent);}',
            '.xsact-ca-toggle input:checked + .xsact-ca-toggle-track::before{transform:translateX(16px);}',
            '.xsact-ca-toggle input:focus + .xsact-ca-toggle-track{box-shadow:0 0 0 2px rgba(var(--xs-accent-rgb),0.35);}',
            '.xsact-beta-badge{font-size:9px;font-weight:700;line-height:1;padding:2px 5px;border-radius:6px;margin-left:5px;color:#FFD27A;background:rgba(255,180,60,0.16);border:1px solid rgba(255,180,60,0.4);vertical-align:middle;white-space:nowrap;}',
            '.xsact-ca-btns{display:flex;gap:6px;flex-shrink:0;}',
            '.xsact-ca-btns button{width:32px;height:32px;display:flex;align-items:center;justify-content:center;border-radius:8px;border:1px solid var(--xs-border);background:var(--xs-btn-bg);color:var(--xs-text-dim);cursor:pointer;transition:background .15s,color .15s,border-color .15s;}',
            '.xsact-ca-btns button:hover{background:var(--xs-hover);color:var(--xs-text);border-color:var(--xs-border-strong);}',
            '.xsact-ca-run:hover{background:rgba(70,224,160,0.16);color:#5FE3B0;border-color:rgba(70,224,160,0.5);}',
            '.xsact-ca-delete:hover{background:rgba(255,92,92,0.16);color:#FF9C9C;border-color:rgba(255,92,92,0.5);}',
            '.xsact-ca-empty{padding:36px 14px;}',

            '.xsact-ca-editor{display:flex;flex-direction:column;gap:14px;width:100%;min-width:0;}',
            '.xsact-ca-editor .xsact-combo-field{display:flex;flex-direction:column;gap:7px;padding:13px 14px;background:var(--xs-panel-bg-2);border:1px solid var(--xs-border);border-radius:10px;}',
            '.xsact-ca-editor .xsact-combo-field label{font-size:11px;font-weight:600;color:var(--xs-accent-text);letter-spacing:0.04em;text-transform:uppercase;}',
            '.xsact-ca-editor .xsact-combo-field input,.xsact-ca-editor .xsact-combo-field textarea,.xsact-ca-editor .xsact-combo-field select,.xsact-ca-editor .xsact-combo-field .xsact-ca-dialog-rich{width:100%;padding:10px 12px;border-radius:8px;border:1px solid var(--xs-border-strong);background:var(--xs-input-bg);color:var(--xs-text);font-size:13px;box-sizing:border-box;font-family:inherit;}',
            '.xsact-ca-editor .xsact-combo-field input:focus,.xsact-ca-editor .xsact-combo-field textarea:focus,.xsact-ca-editor .xsact-combo-field select:focus,.xsact-ca-editor .xsact-combo-field .xsact-ca-dialog-rich:focus{outline:none;border-color:var(--xs-accent);}',
            '.xsact-ca-editor textarea{resize:vertical;min-height:54px;line-height:1.5;}',
            '.xsact-ca-scope{display:flex;gap:8px;}',
            '.xsact-ca-scope button{flex:1;padding:9px 10px;border-radius:8px;border:1px solid var(--xs-border);background:var(--xs-btn-bg);color:var(--xs-text-dim);cursor:pointer;font-size:12px;font-weight:500;transition:all .15s;}',
            '.xsact-ca-scope button:hover{background:var(--xs-hover);border-color:var(--xs-border-strong);color:var(--xs-text);}',
            '.xsact-ca-scope button.active{background:rgba(255,92,122,0.18);border-color:rgba(255,92,122,0.55);color:#FFB3C6;font-weight:600;}',
            '.xsact-ca-hint{display:flex;align-items:baseline;justify-content:flex-start;gap:8px;flex-wrap:wrap;padding:10px 14px;border-radius:10px;border:1px solid var(--xs-border-strong);background:var(--xs-panel-bg-2);box-shadow:0 1px 4px rgba(0,0,0,0.08);}',
            '.xsact-ca-hint-title{font-size:12px;font-weight:600;color:var(--xs-accent-text);letter-spacing:0.04em;text-transform:uppercase;white-space:nowrap;line-height:1;}',
            '.xsact-ca-hint-btns{display:flex;gap:8px;flex-wrap:wrap;}',
            '.xsact-ca-token{display:inline-flex;align-items:center;gap:6px;padding:6px 12px;border-radius:999px;border:1px solid var(--xs-border);background:var(--xs-input-bg);color:var(--xs-text);font-size:12px;font-weight:500;cursor:pointer;transition:all .15s ease;white-space:nowrap;user-select:none;-webkit-user-select:none;box-shadow:0 1px 2px rgba(0,0,0,0.08);}',
            '.xsact-ca-token:hover{background:rgba(255,92,122,0.12);border-color:rgba(255,92,122,0.5);color:#FFD6DF;box-shadow:0 2px 8px rgba(255,92,122,0.18);transform:translateY(-1px);}',
            '.xsact-ca-token:active{transform:translateY(0) scale(0.97);box-shadow:0 1px 3px rgba(255,92,122,0.12);}',
            '.xsact-ca-token-dot{width:7px;height:7px;border-radius:50%;box-shadow:inset 0 0 0 1px rgba(255,255,255,0.12);}',
            '.xsact-ca-token-dot.self{background:#46E0A0;}',
            '.xsact-ca-token-dot.other{background:#FF5C7A;}',
            '.xsact-ca-part-display{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 12px;border-radius:8px;border:1px solid var(--xs-border-strong);background:var(--xs-input-bg);cursor:pointer;transition:background .15s,border-color .15s;}',
            '.xsact-ca-part-display:hover{background:var(--xs-hover);border-color:var(--xs-accent);}',
            '.xsact-ca-part-label{font-size:13px;color:var(--xs-text);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.xsact-ca-part-change{font-size:11px;color:var(--xs-text-dim);white-space:nowrap;flex-shrink:0;}',
            '.xsact-ca-part-map{height:min(240px,42vh);min-height:160px;max-height:300px;border-radius:10px;border:1px solid var(--xs-border);background:var(--xs-panel-bg-2);padding:10px;display:flex;flex-direction:column;align-items:stretch;gap:6px;overflow:hidden;box-sizing:border-box;}',
            '.xsact-body-mini-svg{flex:1;min-height:0;width:100%;height:100%;overflow:visible;filter:var(--xs-zone-filter);}',
            '.xsact-body-mini-hint{font-size:11px;color:var(--xs-text-dim);text-align:center;padding:5px 8px;border-radius:6px;background:var(--xs-panel-bg);border:1px solid var(--xs-border);white-space:nowrap;flex-shrink:0;}',
            '.xsact-ca-part-map .xsact-body-part-zone{fill:var(--xs-zone-fill);stroke:var(--xs-zone-stroke);stroke-width:1.2;cursor:pointer;transition:fill .12s,stroke .12s,stroke-width .12s,filter .12s;pointer-events:all;vector-effect:non-scaling-stroke;}',
            '.xsact-ca-part-map .xsact-body-part-zone:hover,.xsact-ca-part-map .xsact-body-part-zone.hover{fill:var(--xs-zone-fill-hover);stroke:var(--xs-zone-stroke-hover);stroke-width:2.5;filter:drop-shadow(0 0 8px rgba(var(--xs-accent-rgb), 0.6));}',
            '.xsact-ca-part-map .xsact-body-part-zone.selected{fill:var(--xs-zone-fill-selected);stroke:var(--xs-zone-stroke-selected);stroke-width:2.5;filter:drop-shadow(0 0 10px rgba(var(--xs-accent-rgb), 0.55));}',
            '.xsact-ca-preview{padding:12px 14px;border-radius:9px;background:rgba(255,92,122,0.08);border:1px dashed rgba(255,92,122,0.35);color:var(--xs-text);font-size:13px;line-height:1.55;white-space:pre-line;}',
            '.xsact-ca-preview::before{content:"效果预览";display:block;font-size:10px;font-weight:600;color:var(--xs-accent-text);letter-spacing:0.04em;text-transform:uppercase;margin-bottom:6px;}',
            '.xsact-ca-editor .xsact-combo-actions{display:flex;gap:8px;margin-top:4px;}',
            '.xsact-ca-editor .xsact-combo-actions button{flex:1;padding:10px 14px;border-radius:8px;cursor:pointer;font-size:13px;font-weight:600;border:none;color:var(--xs-text);transition:background .15s,transform .1s;}',
            '.xsact-ca-editor .xsact-combo-actions button:hover{transform:translateY(-1px);}',
            '.xsact-ca-editor .xsact-combo-save-btn{background:#46E0A0;color:#0B1F18;}',
            '.xsact-ca-editor .xsact-combo-save-btn:hover{background:#2FC989;}',
            '.xsact-ca-editor .xsact-combo-cancel-btn{background:var(--xs-border);color:var(--xs-text);}',
            '.xsact-ca-editor .xsact-combo-cancel-btn:hover{background:var(--xs-border-strong);}',
            '.xsact-ca-del-btn{background:rgba(255,92,92,0.14);color:#FF9C9C;}',
            '.xsact-ca-del-btn:hover{background:rgba(255,92,92,0.24);transform:translateY(-1px);}',

            '.xsact-ca-raw{display:none;}',
            '.xsact-ca-editor .xsact-ca-dialog-rich{min-height:54px;max-height:160px;line-height:1.5;white-space:pre-wrap;word-break:break-word;overflow:auto;outline:none;}',
            '.xsact-ca-editor .xsact-ca-dialog-rich:empty:before{content:attr(data-placeholder);color:var(--xs-text-dim);pointer-events:none;}',
            '.xsact-token-pill{display:inline-flex;align-items:center;background:rgba(255,92,122,0.18);border:1px solid rgba(255,92,122,0.45);color:#FFD6DF;border-radius:5px;padding:1px 5px;font-size:12px;line-height:1;cursor:default;user-select:none;-webkit-user-select:none;vertical-align:baseline;margin:0 2px;}',
            '.xsact-zwsp{display:inline;font-size:0;line-height:0;}',

            /* 底部操作栏 */
            '.xsact-qa-panel-footer{',
            '  display:flex;align-items:center;flex-wrap:wrap;gap:7px;padding:11px 12px;border-top:1px solid var(--xs-border);min-height:0;',
            '}',
            '.xsact-qa-mini-btn{',
            '  background:var(--xs-btn-bg);border:1px solid var(--xs-border);',
            '  border-radius:8px;padding:8px 10px;font-size:12px;color:var(--xs-text-dim);cursor:pointer;',
            '  display:flex;align-items:center;justify-content:center;gap:6px;transition:background .15s,border-color .15s,color .15s,box-shadow .15s;',
            '}',
            '.xsact-qa-mini-btn:hover{background:var(--xs-hover);border-color:var(--xs-border-strong);color:var(--xs-text);}',
            '#xsact-refresh-btn,#xsact-exit-panel-btn{padding:0;width:28px;height:28px;}',
            '#xsact-x3-btn{padding:8px 10px;min-width:34px;}',
            /* 版本号隐约显示（footer 右下，hover 才清晰） */
            '.xsact-version-tag{',
            '  margin-left:auto;font-size:10px;line-height:1;letter-spacing:.04em;user-select:none;',
            '  color:rgba(var(--xs-accent-rgb),0.9);opacity:.32;transition:opacity .25s ease;align-self:center;',
            '}',
            '.xsact-version-tag:hover{opacity:.72;}',
            '.xsact-toggle-pill{gap:5px;padding:8px 10px;}',
            '.xsact-toggle-pill .xsact-ico{width:14px;height:14px;stroke-width:2.2px;}',
            '.xsact-pill-dot{width:7px;height:7px;border-radius:50%;background:var(--xs-text-faint);border:1px solid var(--xs-border-strong);transition:background .15s,box-shadow .15s,border-color .15s;}',
            '.xsact-qa-mini-btn.on{color:#E8B339;border-color:rgba(232,179,57,0.6);background:rgba(232,179,57,0.12);box-shadow:0 0 10px rgba(232,179,57,0.12);}',
            '.xsact-toggle-pill.on .xsact-pill-dot{background:#E8B339;border-color:#E8B339;box-shadow:0 0 8px rgba(232,179,57,0.7);}',
            '#xsact-fav-btn.on{color:#E8B339;background:rgba(232,179,57,0.12);border-color:rgba(232,179,57,0.6);}',
            '#xsact-fav-btn.on .xsact-pill-dot{background:#E8B339;border-color:#E8B339;}',
            '#xsact-self-btn.on{color:#46E0A0;border-color:rgba(70,224,160,0.6);background:rgba(70,224,160,0.12);}',
            '#xsact-self-btn.on .xsact-pill-dot{background:#46E0A0;border-color:#46E0A0;box-shadow:0 0 8px rgba(70,224,160,0.7);}',
            '#xsact-fav-clear-btn{padding:0;width:28px;height:28px;color:var(--xs-text-dim);}',
            '#xsact-fav-clear-btn:hover{background:rgba(255,92,92,0.12);border-color:rgba(255,92,92,0.5);color:#FFB3B3;}',

            '.xsact-qa-panel-content{',
            '  flex:1;position:relative;display:flex;flex-direction:column;min-width:0;',
            '  overflow:hidden;min-height:0;',
            '}',
            '.xsact-qa-panel-main{',
            '  flex:1;display:flex;flex-direction:column;min-width:0;min-height:0;',
            '}',

            /* ===== 人物列表侧边触发按钮（左向小三角）===== */
            '#xsact-char-popover-tab{',
            '  position:absolute;left:-16px;top:50%;transform:translateY(-50%);',
            '  width:16px;height:56px;',
            '  display:flex;align-items:center;justify-content:center;',
            '  background:var(--xs-panel-bg);border:1px solid var(--xs-border);border-right:none;',
            '  border-radius:8px 0 0 8px;',
            '  color:var(--xs-text-dim);cursor:pointer;',
            '  z-index:90001;',
            '  box-shadow:-4px 0 14px rgba(0,0,0,0.22);',
            '  transition:all .15s ease;',
            '}',
            '#xsact-char-popover-tab:hover,',
            '#xsact-char-popover-tab.active{',
            '  color:var(--xs-accent);border-color:var(--xs-accent);',
            '  box-shadow:0 0 12px rgba(var(--xs-accent-rgb), 0.35), -4px 0 14px rgba(0,0,0,0.22);',
            '}',
            '#xsact-char-popover-tab .xsact-ico{width:10px;height:10px;}',

            /* 左右窗口联动桥接 */
            '#xsact-popover-connector{',
            '  display:none;position:absolute;left:-16px;top:50%;',
            '  width:16px;height:80px;transform:translateY(-50%);',
            '  background:linear-gradient(to right, rgba(var(--xs-accent-rgb),0.15), rgba(var(--xs-accent-rgb),0.55));',
            '  border-top:1px solid rgba(var(--xs-accent-rgb),0.55);',
            '  border-bottom:1px solid rgba(var(--xs-accent-rgb),0.55);',
            '  box-shadow:0 0 16px rgba(var(--xs-accent-rgb), 0.35);',
            '  z-index:90000;',
            '}',
            '#xsact-popover-connector::after{',
            '  content:"";position:absolute;left:5px;top:50%;transform:translateY(-50%);',
            '  width:0;height:0;',
            '  border-top:4px solid transparent;',
            '  border-bottom:4px solid transparent;',
            '  border-left:5px solid rgba(var(--xs-accent-rgb),0.85);',
            '}',
            '#xsact-qa-panel.popover-open #xsact-popover-connector{display:block;}',

            /* ===== 人物列表弹出层 ===== */
            '.xsact-char-popover{',
            '  position:absolute;left:-256px;top:46px;',
            '  width:min(260px,85vw);height:calc(100% - 64px);',
            '  display:flex;flex-direction:column;min-height:0;',
            '  background:var(--xs-panel-bg);',
            '  border:1px solid var(--xs-accent);border-radius:12px;',
            '  box-shadow:0 12px 40px rgba(0,0,0,0.45),0 0 0 1px rgba(var(--xs-accent-rgb), 0.08),0 0 24px rgba(var(--xs-accent-rgb), 0.10);',
            '  backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);',
            '  z-index:10;overflow:hidden;',
            '  animation:xsact-popover-in .2s cubic-bezier(.16,1,.3,1);',
            '}',
            '.xsact-char-popover.right{',
            '  left:calc(100% + 16px);',
            '}',
            '.xsact-char-popover.show-back .xsact-char-popover-back{display:flex;}',
            '.xsact-char-popover-header{',
            '  display:flex;justify-content:space-between;align-items:center;gap:6px;',
            '  padding:10px 12px;border-bottom:1px solid var(--xs-border);',
            '  background:rgba(var(--xs-accent-rgb), 0.08);',
            '}',
            '.xsact-char-popover-back{',
            '  display:none;width:22px;height:22px;align-items:center;justify-content:center;',
            '  background:transparent;border:1px solid transparent;border-radius:6px;',
            '  color:var(--xs-text-dim);font-size:20px;line-height:1;cursor:pointer;',
            '  transition:all .15s ease;',
            '}',
            '.xsact-char-popover-back:hover{',
            '  background:var(--xs-hover);color:var(--xs-text);',
            '}',
            '.xsact-char-popover-title{',
            '  flex:1;font-size:13px;font-weight:600;color:var(--xs-accent-text);',
            '  overflow:hidden;text-overflow:ellipsis;white-space:nowrap;',
            '}',
            '.xsact-char-popover-close{',
            '  width:22px;height:22px;display:flex;align-items:center;justify-content:center;',
            '  background:transparent;border:1px solid transparent;border-radius:6px;',
            '  color:var(--xs-text-dim);font-size:17px;line-height:1;cursor:pointer;',
            '  transition:all .15s ease;',
            '}',
            '.xsact-char-popover-close:hover{',
            '  background:rgba(255,92,92,0.12);border-color:rgba(255,92,92,0.4);color:#FFB3B3;',
            '}',
            '.xsact-char-popover-body{',
            '  flex:1;overflow-y:auto;overflow-x:hidden;scrollbar-width:thin;scrollbar-color:var(--xs-scroll) transparent;overscroll-behavior:contain;',
            '  display:flex;flex-direction:column;min-height:0;',
            '}',
            '.xsact-char-popover-body::-webkit-scrollbar{width:4px;}',
            '.xsact-char-popover-body::-webkit-scrollbar-track{background:transparent;}',
            '.xsact-char-popover-body::-webkit-scrollbar-thumb{background:var(--xs-scroll);border-radius:2px;}',
            '.xsact-char-popover-items{',
            '  flex:1;overflow-y:auto;scrollbar-width:thin;scrollbar-color:var(--xs-scroll) transparent;',
            '  padding:6px;',
            '}',
            '.xsact-char-popover-items::-webkit-scrollbar{width:4px;}',
            '.xsact-char-popover-items::-webkit-scrollbar-track{background:transparent;}',
            '.xsact-char-popover-items::-webkit-scrollbar-thumb{background:var(--xs-scroll);border-radius:2px;}',
            '.xsact-char-popover-empty{',
            '  padding:16px 10px;font-size:12px;color:var(--xs-text-faint);text-align:center;',
            '}',
            '.xsact-char-popover-item{',
            '  display:flex;align-items:center;gap:8px;',
            '  padding:9px 10px;margin-bottom:4px;',
            '  border-radius:8px;cursor:pointer;',
            '  background:var(--xs-panel-bg-2);border:1px solid var(--xs-border);',
            '  color:var(--xs-text-dim);font-size:12.5px;',
            '  transition:all .12s ease;',
            '}',
            '.xsact-char-popover-item:last-child{margin-bottom:0;}',
            '.xsact-char-popover-item:hover{',
            '  background:var(--xs-hover);border-color:var(--xs-border-strong);color:var(--xs-text);',
            '  transform:translateX(3px);',
            '}',
            '.xsact-char-popover-item.selected{',
            '  background:rgba(var(--xs-accent-rgb), 0.14);border-color:var(--xs-accent);',
            '  color:var(--xs-accent-text);',
            '}',
            '.xsact-char-popover-item.self{',
            '  color:#46E0A0;border-color:rgba(70,224,160,0.25);',
            '}',
            '.xsact-char-popover-item.self:hover{',
            '  background:rgba(70,224,160,0.08);border-color:rgba(70,224,160,0.5);color:#CFFAE8;',
            '}',
            '.xsact-char-popover-item.self.selected{',
            '  background:rgba(70,224,160,0.14);border-color:#46E0A0;color:#46E0A0;',
            '}',
            '.xsact-char-popover-name{',
            '  flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;',
            '}',
            '.xsact-char-popover-self{',
            '  flex-shrink:0;font-size:9px;padding:2px 5px;border-radius:4px;',
            '  background:rgba(70,224,160,0.15);color:#46E0A0;',
            '}',
            '@keyframes xsact-popover-in{',
            '  from{opacity:0;transform:translateY(-8px) scale(.96);}',
            '  to{opacity:1;transform:translateY(0) scale(1);}',
            '}',

            /* ===== 人物部位选择（BC 原生矩形 Zone 地图）===== */
            '.xsact-body-select{',
            '  flex:1;display:flex;flex-direction:column;align-items:stretch;min-height:0;',
            '  min-height:0;padding:6px 4px 0;gap:6px;overflow:hidden;',
            '}',
            '.xsact-body-svg{',
            '  flex:1;min-height:0;width:100%;height:100%;',
            '  align-self:center;overflow:visible;',
            '  filter:var(--xs-zone-filter);',
            '}',
            /* 矩形热区：主题感知描边；light 下深灰/玫红，dark 下保持白色霓虹 */
            '.xsact-body-part-zone{',
            '  fill:var(--xs-zone-fill);',
            '  stroke:var(--xs-zone-stroke);stroke-width:1.2;',
            '  cursor:pointer;transition:fill .12s,stroke .12s,stroke-width .12s,filter .12s;',
            '  pointer-events:all;vector-effect:non-scaling-stroke;',
            '}',
            '.xsact-body-part-zone:hover,.xsact-body-part-zone.hover{',
            '  fill:var(--xs-zone-fill-hover);stroke:var(--xs-zone-stroke-hover);stroke-width:2.5;',
            '  filter:drop-shadow(0 0 8px rgba(var(--xs-accent-rgb), 0.6));',
            '}',
            '.xsact-body-part-zone.selected{',
            '  fill:var(--xs-zone-fill-selected);',
            '  stroke:var(--xs-zone-stroke-selected);stroke-width:2.5;',
            '  filter:drop-shadow(0 0 10px rgba(var(--xs-accent-rgb), 0.55));',
            '}',
            '.xsact-body-part-hint{',
            '  font-size:12px;color:var(--xs-text-dim);text-align:center;',
            '  padding:6px 10px;border-radius:6px;background:var(--xs-panel-bg-2);',
            '  border:1px solid var(--xs-border);white-space:nowrap;',
            '}',
            /* 预设栏 */
            '.xsact-qa-panel-body.fav-active .xsact-action-btn:hover{',
            '  border-style:dashed;border-color:rgba(232,179,57,0.7);',
            '}',
            '.xsact-qa-state.presets-bar{grid-column:1 / -1;padding:6px 12px 10px;display:flex;flex-wrap:wrap;gap:4px;}',

            '.xsact-resize-handle{',
            '  position:absolute;right:4px;bottom:4px;width:18px;height:18px;',
            '  display:flex;align-items:flex-end;justify-content:flex-end;',
            '  color:var(--xs-text-faint);cursor:nwse-resize;z-index:10;transition:color .15s;',
            '  pointer-events:auto;',
            '}',
            '.xsact-resize-handle:hover{color:var(--xs-accent);}',
            '.xsact-resize-handle.resizing{color:var(--xs-accent);}',
            '.xsact-resize-handle .xsact-ico{width:14px;height:14px;}',

            /* ===== 浮动身体网格（霓虹线框，按 BC 原生 Zone 定位） ===== */
            '.xsact-body-grid{',
            '  position:absolute;z-index:89999;pointer-events:none;',
            '  background:transparent !important;',
            '}',
            '.xsact-part-btn{',
            '  position:absolute;padding:0;margin:0;',
            '  background:transparent;color:transparent;font-size:0;border:none;',
            '  cursor:pointer;transition:box-shadow 0.12s ease;box-sizing:border-box;',
            '  pointer-events:auto;',
            '  box-shadow:inset 0 0 0 2px rgba(77,248,255,0.55),',
            '             0 0 6px rgba(77,248,255,0.18);',
            '}',
            '.xsact-part-btn:hover{',
            '  box-shadow:inset 0 0 0 3px rgba(77,248,255,1),',
            '             0 0 18px rgba(77,248,255,0.6),0 0 36px rgba(77,248,255,0.2);',
            '}',
            '.xsact-part-btn.active{',
            '  box-shadow:inset 0 0 0 3.5px rgba(255,51,102,1),',
            '             0 0 22px rgba(255,51,102,0.75),0 0 44px rgba(255,51,102,0.35),',
            '             inset 0 0 24px rgba(255,51,102,0.12);',
            '}',
            '.xsact-part-btn.active:hover{',
            '  box-shadow:inset 0 0 0 4.5px #FF3366,',
            '             0 0 30px rgba(255,51,102,1),0 0 60px rgba(255,51,102,0.45);',
            '}',

            /* 自己模式：给玩家自己的身体线框加个绿色边框提示 */
            '.xsact-body-grid.self .xsact-part-btn{',
            '  box-shadow:inset 0 0 0 2px rgba(70,224,160,0.65),',
            '             0 0 6px rgba(70,224,160,0.25);',
            '}',
            '.xsact-body-grid.self .xsact-part-btn:hover{',
            '  box-shadow:inset 0 0 0 3px rgba(70,224,160,1),',
            '             0 0 18px rgba(70,224,160,0.55),0 0 36px rgba(70,224,160,0.25);',
            '}',

            /* ===== 滚动条 ===== */
            '.xsact-qa-panel-body::-webkit-scrollbar{width:6px;}',
            '.xsact-qa-panel-body::-webkit-scrollbar-track{background:transparent;}',
            '.xsact-qa-panel-body::-webkit-scrollbar-thumb{background:var(--xs-scroll);border-radius:3px;}',

            /* ===== 容器查询：面板内容按实际宽度自适应 ===== */
            '@container xsact-body (max-width: 180px){',
              '.xsact-qa-panel-body{grid-template-columns:1fr;}',
              '.xsact-action-btn{padding:10px 9px;font-size:11.5px;}',
            '}',
            '@container xsact-body (min-width: 181px) and (max-width: 280px){',
              '.xsact-qa-panel-body{grid-template-columns:repeat(2,1fr);}',
            '}',
            '@container xsact-body (min-width: 281px){',
              '.xsact-qa-panel-body{grid-template-columns:repeat(auto-fill, minmax(108px, 1fr));}',
            '}',
            '@container xsact-panel (max-width: 280px){',
              '.xsact-qa-panel-footer .xsact-qa-mini-btn span:not(.xsact-pill-dot){display:none;}',
              '.xsact-qa-panel-footer .xsact-qa-mini-btn{flex:0 0 36px;padding:6px;}',
              '.xsact-qa-mode-tabs .xsact-mode-tab span{display:none;}',
              '.xsact-mode-tab .xsact-ico{width:16px;height:16px;}',
            '}',
            '@container xsact-panel (max-width: 240px){',
              '.xsact-panel-head-actions button:not(#xsact-exit-panel-btn){display:none;}',
            '}',

            /* ===== 主题色切换过渡 ===== */
            '#xsact-qa-panel,#xsact-toggle-btn{',
            '  transition:background-color .3s ease,border-color .3s ease,color .3s ease,box-shadow .3s ease;',
            '}',
            '#xsact-qa-panel{animation:xsact-pop-in .28s cubic-bezier(.16,1,.3,1);}',

            /* ===== 过渡动画 ===== */
            '@keyframes xsact-pop-in{from{opacity:0;transform:translateY(-8px) scale(.98);}to{opacity:1;transform:none;}}',
            '@keyframes xsact-fade-in{from{opacity:0;transform:translateY(4px);}to{opacity:1;transform:none;}}',
            '.xsact-action-btn,.xsact-combo-card{animation:xsact-fade-in .22s ease both;}',

            /* 主题切换按钮图标显隐 */
            '#xsact-theme-btn .xsact-theme-icon{display:none;}',
            '[data-xsact-theme="dark"] #xsact-theme-btn .sun{display:block;}',
            '[data-xsact-theme="light"] #xsact-theme-btn .moon{display:block;}',

            /* ===== 视口断点适配（手机/平板/笔记本/大屏） ===== */
            '@media (max-width: 480px){',
              '#xsact-qa-panel{',
                'width:92vw;height:88vh;top:6vh;right:4vw;left:auto;bottom:auto;',
                'min-width:200px;min-height:260px;max-width:98vw;max-height:94vh;',
              '}',
              '#xsact-qa-panel.popover-open #xsact-popover-connector{display:none;}',
              '#xsact-char-popover-tab{display:none;}',
              '.xsact-char-popover,',
              '.xsact-char-popover.right{',
                'position:absolute;left:0;top:0;width:100%;height:100%;border-radius:14px;',
                'border-color:var(--xs-accent);animation:xsact-popover-in .2s cubic-bezier(.16,1,.3,1);',
              '}',
              '.xsact-qa-panel-header{padding:12px 14px;}',
              '#xsact-panel-title{font-size:14px;}',
              '.xsact-qa-mode-tabs{padding:10px 14px;}',
              '.xsact-mode-tab{padding:12px 10px;font-size:13px;}',
              '.xsact-qa-panel-body{padding:12px 14px;gap:8px;}',
              '.xsact-action-btn{padding:14px 12px;font-size:14px;}',
              '.xsact-qa-panel-footer{padding:10px 14px;gap:8px;}',
              '.xsact-qa-mini-btn{flex:1 1 0;min-height:44px;padding:10px 8px;font-size:13px;}',
              '#xsact-fav-clear-btn{flex:0 0 44px;}',
              '.xsact-body-select{padding:8px 6px;}',
              '.xsact-body-part-hint{font-size:13px;}',
            '}',
            '@media (min-width: 481px) and (max-width: 768px){',
              '#xsact-qa-panel{width:min(340px,90vw);height:min(640px,86vh);}',
              '.xsact-action-btn{padding:11px 12px;font-size:13px;}',
            '}',
            '@media (min-width: 769px) and (max-width: 1200px){',
              '#xsact-qa-panel{width:min(360px,40vw);height:min(680px,84vh);}',
            '}',
            '@media (min-width: 1201px){',
              '#xsact-qa-panel{width:min(380px,30vw);height:min(720px,82vh);}',
            '}',
            '@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi){',
              '.xsact-qa-panel-header,.xsact-qa-panel-footer,.xsact-action-btn,.xsact-char-popover-item{-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}',
            '}',
            /* ===== light 主题下高对比文字修正 ===== */
            '[data-xsact-theme="light"] .xsact-action-btn.fav{ color:#7D5A10; }',
            '[data-xsact-theme="light"] .xsact-action-btn.fav:hover{ color:#5C4508; }',
            '[data-xsact-theme="light"] .xsact-add-to-combo{ color:#1B7A5C; }',
            '[data-xsact-theme="light"] .xsact-add-to-combo:hover{ color:#0F5C44; }',
            '[data-xsact-theme="light"] #xsact-self-btn.on{ color:#1B7A5C; }',
            '[data-xsact-theme="light"] .xsact-char-popover-item.self{ color:#1B7A5C; }',
            '[data-xsact-theme="light"] .xsact-char-popover-item.self:hover{ color:#0F5C44; }',
            '[data-xsact-theme="light"] .xsact-char-popover-item.self.selected{ color:#1B7A5C; }',
            /* ── 更新 / 公告横幅 ── */
            '.xsact-update-banner{',
            '  margin:8px 10px 0;border:1px solid var(--xs-accent, rgba(255,92,122,0.6));border-radius:10px;',
            '  background:linear-gradient(180deg, rgba(255,92,122,0.14), rgba(255,92,122,0.06));',
            '  padding:8px 10px;font-size:12px;color:var(--xs-text);box-shadow:0 4px 14px rgba(0,0,0,0.25);',
            '}',
            '.xsact-update-banner.is-announce{',
            '  border-color:rgba(120,180,255,0.55);background:linear-gradient(180deg, rgba(120,180,255,0.14), rgba(120,180,255,0.05));',
            '}',
            '.xsact-update-banner.is-important{',
            '  border-color:#ffcf5c;background:linear-gradient(180deg, rgba(255,207,92,0.16), rgba(255,207,92,0.06));',
            '}',
            '.xsact-update-banner.is-available{',
            '  border-color:var(--xs-accent, rgba(255,92,122,0.6));background:linear-gradient(180deg, rgba(255,92,122,0.14), rgba(255,92,122,0.06));',
            '}',
            '.xsact-update-banner.is-available .xsact-ub-tag{color:var(--xs-accent, #FF5C7A);}',
            '.xsact-ub-head{display:flex;align-items:center;gap:6px;margin-bottom:4px;}',
            '.xsact-ub-tag{font-weight:700;letter-spacing:.04em;color:var(--xs-accent, #FF5C7A);}',
            '.xsact-update-banner.is-announce .xsact-ub-tag{color:#7ab8ff;}',
            '.xsact-ub-ver{font-weight:700;}',
            '.xsact-ub-title{font-weight:600;}',
            '.xsact-ub-close{margin-left:auto;background:none;border:none;color:var(--xs-text-dim);font-size:16px;line-height:1;cursor:pointer;padding:0 4px;}',
            '.xsact-ub-close:hover{color:var(--xs-text);}',
            '.xsact-ub-sum{margin:2px 0 6px;padding-left:16px;color:var(--xs-text-dim);}',
            '.xsact-ub-sum li{margin:1px 0;}',
            '.xsact-ub-msg{margin:2px 0 6px;color:var(--xs-text-dim);line-height:1.4;white-space:pre-line;}',
            '.xsact-ub-actions{display:flex;gap:6px;flex-wrap:wrap;}',
            '.xsact-ub-btn{background:var(--xs-btn-bg, rgba(255,255,255,0.08));border:1px solid var(--xs-border, rgba(255,255,255,0.12));',
            '  color:var(--xs-text);border-radius:7px;padding:4px 9px;font-size:12px;cursor:pointer;}',
            '.xsact-ub-btn:hover{background:var(--xs-hover, rgba(255,255,255,0.14));}',
            '.xsact-ub-primary{background:var(--xs-accent, #FF5C7A);border-color:transparent;color:#fff;font-weight:600;}',
            '.xsact-ub-primary:hover{filter:brightness(1.08);}',
            '@media (max-width:480px){',
            '  .xsact-update-banner{font-size:11px;}',
            '}',

            /* ===== 自定义 tooltip（替换原生 title：统一风格 / 视口翻转 / 短延迟） ===== */
            '.xsact-tooltip{',
            '  position:fixed;z-index:100001;max-width:240px;',
            '  padding:6px 10px;border-radius:9px;',
            '  background:var(--xs-panel-bg);color:var(--xs-text);',
            '  font-size:12px;line-height:1.45;white-space:normal;',
            '  border:1px solid var(--xs-border-strong);',
            '  box-shadow:0 6px 20px var(--xs-shadow);',
            '  backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);',
            '  pointer-events:none;opacity:0;transform:translateY(3px);',
            '  transition:opacity .12s ease,transform .12s ease;',
            '}',
            '.xsact-tooltip.show{opacity:1;transform:translateY(0);}',
            '.xsact-tooltip .xsact-tt-title{font-weight:600;}',
            '.xsact-tooltip .xsact-tt-sub{display:block;margin-top:2px;color:var(--xs-text-dim);font-size:11px;line-height:1.4;}',
            '.xsact-tooltip.is-danger{border-color:#ff6b6b;box-shadow:0 6px 20px var(--xs-shadow),0 0 0 1px rgba(255,107,107,0.25);}',
            '.xsact-tooltip.is-danger .xsact-tt-sub{color:#ffb3b3;}',
        ].join('\n');
        document.head.appendChild(css);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 自定义 tooltip：替换原生 title（仅作用于本插件 UI，不触达 BC 原生提示）
    // 设计要点：
    //  · 事件委托在 document（bubble），靠 isPluginTip() 限定作用域，BC 自身 title 完全不受影响
    //  · 读 data-tooltip 优先（支持 @@ 分隔的「标题@@副标题」），title 兜底
    //  · 悬停时用空格占位抑制原生 title（保留属性存在，closest 仍匹配；移出按条件还原，不覆盖逻辑动态改写的 title）
    //  · 动态定位 + 视口翻转（上方空间不足翻到下方、超出左右则夹取），固定间距不随光标抖动
    //  · 120ms 短延迟显隐；scroll 时隐藏避免错位
    // ─────────────────────────────────────────────────────────────────────────
